export const HTTP_PORT = "HTTP_PORT";
export const SECRET_KEY_BEARER = "SECRET_KEY_BEARER";
export const SECRET_KEY_BEARER_REFRESH = "SECRET_KEY_BEARER_REFRESH";

export const DATABASE_CONFG = "DATABASE_CONFG";
export const DEV_KEY = "dev";
